language: c
addons:
  apt:
    packages:
    - p7zip-full
install:
  - wget https://github.com/emilf/travis-ci-deps-for-emw/raw/master/deps.zip
  - 7z e -y -pqwerty12345 deps.zip
  - ./extract-and-patch-WICED
  - cd WICED-SDK-3.3.1
env:
  - EMW316X=EMW3165
  - EMW316X=EMW3162
script:
  - ./make $EMW316X-FreeRTOS-LwIP-snip.apsta