language: c
addons:
  apt:
    packages:
    - p7zip-full
install:
  - curl https://github.com/emilf/travis-ci-deps-for-emw/raw/master/deps.zip -o deps.zip
  - 7z e -y -pqwerty12345 deps.zip
  - ./extract-and-patch-WICED
script:
  - ./make EMW3165-FreeRTOS-LwIP-snip.apsta