language: c
addons:
  apt:
    packages:
    - p7zip
    - p7zip-full
    - p7zip-rar
install:
  - wget https://github.com/emilf/travis-ci-deps-for-emw/raw/master/deps.zip
  - 7z e -y -pqwerty12345 deps.zip
  - ./extract-and-patch-WICED
  - cd WICED-SDK-3.3.1
env:
  # Generated in bash with:
  # for i in $(ls -d */*/); do echo - APP="${i%%/}"; done | cut -f1,2 -d'/' --output-delimiter=.
  # You need to add the two leading spaces on each line.
  # This is not generated dynamically, so builds can run in parallel.

#  - APP=demo.appliance
  - APP=snip.amqp
  - APP=snip.amqps
  - APP=snip.ap_clients_rssi
  - APP=snip.apsta
  - APP=snip.config_mode
  - APP=snip.crypto
  - APP=snip.dct_read_write
  - APP=snip.email
  - APP=snip.gpio
  - APP=snip.https_client
  - APP=snip.keep_alive
  - APP=snip.link_status
  - APP=snip.mqtt_publisher
  - APP=snip.mqtt_subscriber
  - APP=snip.ota_fr
  - APP=snip.packet_filter
  - APP=snip.ping_powersave
  - APP=snip.ping_webserver
  - APP=snip.scan
  - APP=snip.security_types
  - APP=snip.service_discovery
  - APP=snip.sntp_get_time
  - APP=snip.stack_overflow
  - APP=snip.stdio
  - APP=snip.tcp_client
  - APP=snip.tcp_client_powersave
  - APP=snip.tcp_server
  - APP=snip.tcp_server_async
  - APP=snip.tftp
  - APP=snip.thread_monitor
  - APP=snip.uart
  - APP=snip.udp_receive
  - APP=snip.udp_transmit
  - APP=snip.wps_enrollee
  - APP=snip.wps_registrar
  - APP=test.iperf_app
  - APP=test.mfg_test
#  - APP=wwd.appliance
  - APP=wwd.ping
  - APP=wwd.scan
matrix:
  allow_failures:
    - env: "APP=snip.gpio"
script:
  - ./make EMW3165-$APP
  - ./make EMW3162-$APP
