#!/bin/bash
set -e
WICED_DIR='WICED-SDK-3.3.1'
WICED_ARCHIVE_EXT='.7z.zip'

echo
echo -- WICED 3.3.1 patcher for MXCHIP EMW modules --
echo ------------------------------------------------

if [ -e $WICED_DIR ]; then 
	echo 
	echo === ERROR: The $WICED_DIR directory already exists.
	echo ===        Operation aborted, for your safety.
	echo ===        
	echo ===        Delete the $WICED_DIR directory to proceed.
	exit -1
fi

echo 
echo === Decompressing WICED
unzip $WICED_DIR$WICED_ARCHIVE_EXT >> /dev/null
7z x *.7z >> /dev/null
rm *.7z

echo 
echo === Installing the EMW3162 platform
cp -r patches/EMW3162 $WICED_DIR/platforms

echo 
echo === Installing the EMW3165 platform
cp -r patches/EMW3165 $WICED_DIR/platforms

echo 
echo === Adding SWD and Stlink-v2 support
echo === Use JTAG=stlink-v2 on the make command line to use Stlink-v2
cp -r patches/OpenOCD/* $WICED_DIR/tools/OpenOCD

if [ "`uname`" == "Linux" ]; then

	echo
	echo "=== Replacing WICED make binary with system one (see http://community.broadcom.com/message/17899#17899)"
	# Yea yea... you're not going to be using both anyway :p
	cp /usr/bin/make $WICED_DIR/tools/common/Linux64
        cp /usr/bin/make $WICED_DIR/tools/common/Linux32

	echo 
	echo === Adding udev rules to enable J-Link and st-link-v2 from userspace
	echo === Please enter your password if prompted
	sudo cp patches/*.rules /etc/udev/rules.d
fi

echo
echo ===
echo === Finished decompressing and patching $WICED_DIR for MXCHIP EMW
echo === Refer to the README.md and the Github Wiki for info on how to flash.
echo === Support is also available on our Gitter.im channel at: 
echo === https://gitter.im/MXCHIP-EMW/WICED-for-EMW 
echo ===
